# Generated by Django 6.0.7 on 2026-08-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas', '0002_detallesalida_codigo_tarifa_iva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='actividad_tributaria',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='salida',
            name='tiene_licencia_anual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salida',
            name='tiene_registro_turismo',
            field=models.BooleanField(default=False),
        ),
    ]
