# Generated by Django 6.0.7 on 2026-08-27 01:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas', '0003_salida_actividad_tributaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
