# Generated by Django 6.0.7 on 2026-07-20 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0003_alter_producto_options_alter_producto_costo_and_more'),
        ('proveedores', '0002_alter_proveedor_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Documento')),
                ('fecha', models.DateField(verbose_name='Fecha de Entrada')),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra'), ('DEVOLUCION', 'Devolución'), ('AJUSTE', 'Ajuste de Inventario'), ('DONACION', 'Donación'), ('OTRO', 'Otro')], default='COMPRA', max_length=20, verbose_name='Tipo de Entrada')),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Total')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADA', 'Confirmada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=15, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='proveedores.proveedor', verbose_name='Proveedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Subtotal')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalle_entradas', to='productos.producto')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='entradas.entrada')),
            ],
            options={
                'verbose_name': 'Detalle de Entrada',
                'verbose_name_plural': 'Detalles de Entrada',
            },
        ),
    ]
