# Generated by Django 6.0.7 on 2026-08-27 01:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0002_detalleentrada_codigo_tarifa_iva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de Entrada'),
        ),
    ]
