# Generated by Django 6.0.7 on 2026-08-12 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaIVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código interno de la tarifa de IVA, por ejemplo: IVA_0, IVA_5, IVA_15, IVA_8_TUR.', max_length=20, unique=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje de la tarifa, por ejemplo 0.00, 5.00, 15.00.', max_digits=5)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción del tratamiento tributario y su alcance legal.', max_length=255)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio de vigencia de la tarifa.')),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha de fin de vigencia. Si está vacío, la tarifa se considera vigente indefinidamente.', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si la tarifa está habilitada en el sistema.')),
                ('es_temporal', models.BooleanField(default=False, help_text='Marca si la tarifa es una excepción temporal, como la reducción del 8% para actividades turísticas.')),
            ],
            options={
                'verbose_name': 'Tarifa de IVA',
                'verbose_name_plural': 'Tarifas de IVA',
                'ordering': ['porcentaje', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='ClasificacionTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código interno de clasificación tributaria, por ejemplo: BIEN_NATURAL_0, MATERIAL_CONSTRUCCION_5.', max_length=50, unique=True)),
                ('nombre', models.CharField(help_text='Nombre de la clasificación tributaria.', max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Explicación de qué productos jurídicamente pertenecen a esta clasificación.')),
                ('requiere_documentacion', models.BooleanField(default=False, help_text='Indica si la aplicación de esta clasificación requiere documentación o norma de respaldo.')),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clasificaciones', to='tributacion.tarifaiva')),
            ],
            options={
                'verbose_name': 'Clasificación Tributaria',
                'verbose_name_plural': 'Clasificaciones Tributarias',
                'ordering': ['codigo'],
            },
        ),
    ]
