# Generated by Django 6.0.7 on 2026-08-19 20:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributacion', '0003_seed_tax_classifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasificaciontributaria',
            name='codigo_oficial',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='clasificaciontributaria',
            name='es_material_construccion_listado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clasificaciontributaria',
            name='fundamento_legal',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tarifaiva',
            name='referencia_normativa',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tarifaiva',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje de la tarifa, por ejemplo 0.00, 5.00, 15.00.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='ReglaTemporalIVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('actividad', models.CharField(default='TURISMO', max_length=80)),
                ('referencia_normativa', models.CharField(max_length=255)),
                ('requiere_registro_turismo', models.BooleanField(default=True)),
                ('requiere_licencia_anual', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tributacion.tarifaiva')),
            ],
        ),
    ]
