# Generated by Django 6.0.7 on 2026-08-12 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_options_alter_producto_precio'),
        ('tributacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='clasificacion_tributaria',
            field=models.ForeignKey(blank=True, help_text='Clasificación tributaria explícita que determina la tarifa de IVA del producto.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='tributacion.clasificaciontributaria'),
        ),
    ]
