# Generated by Django 6.0.7 on 2026-08-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_seed_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='EAN, UPC u otro código legible por escáner.', max_length=80, null=True, unique=True, verbose_name='Código de barras'),
        ),
        migrations.AddField(
            model_name='producto',
            name='lote',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Lote'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ubicacion',
            field=models.CharField(blank=True, default='', help_text='Ejemplo: Bodega A, pasillo 2, estante 4.', max_length=120, verbose_name='Ubicación'),
        ),
    ]
