# Generated by Django 6.0.7 on 2026-08-19 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('STOCK', 'Stock bajo'), ('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('SISTEMA', 'Sistema')], default='SISTEMA', max_length=20)),
                ('titulo', models.CharField(max_length=120)),
                ('mensaje', models.TextField()),
                ('url', models.CharField(blank=True, max_length=255)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('enviada_telegram', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='SuscripcionTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_vinculacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificacionLeida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leida', models.DateTimeField(auto_now_add=True)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='telegram_bot.notificacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('notificacion', 'usuario'), name='notificacion_usuario_unica')],
            },
        ),
    ]
